Repository Wase-Engine/wase-engine, pull requests merged in 2021-07, with the labels that each got.

#37 Update readme.md
  documentation.md
  readme.md
Labels: documentation

#46 Removed unnecessary lines
  src/wase/core/draw.cpp
  src/wase/core/engine.cpp
  src/wase/core/renderer.cpp
  src/wase/core/renderer.h
  src/wase/ecs/components/colliders/box_collider_2d.cpp
  src/wase/ecs/components/colliders/box_collider_2d.h
  src/wase/ecs/components/sprite_renderer.cpp
  src/wase/ecs/components/transform.h
Labels: improvement

#47 Added the possibility to set a parent to null
  src/wase/ecs/components/sprite_renderer.cpp
  src/wase/ecs/components/ui/label.cpp
  src/wase/ecs/entity.cpp
Labels: enhancement

#48 Added the possibility to remove a component
  src/wase/ecs/entity.h
Labels: enhancement

#58 Button added
  CMakeLists.txt
  src/wase/core/size.h
  src/wase/ecs/components/colliders/box_collider_2d.cpp
  src/wase/ecs/components/colliders/box_collider_2d.h
  src/wase/ecs/components/ui/button.cpp
  src/wase/ecs/components/ui/button.h
  src/wase/ecs/components/ui/label.h
Labels: enhancement

#63 Added a Button component
  CMakeLists.txt
  src/wase/core/size.h
  src/wase/ecs/components/colliders/box_collider_2d.cpp
  src/wase/ecs/components/colliders/box_collider_2d.h
  src/wase/ecs/components/ui/button.cpp
  src/wase/ecs/components/ui/button.h
  src/wase/ecs/components/ui/label.h
Labels: enhancement

#68 Added MinGW and x64 support (refactored)
  CMakeLists.txt
  src/wase/core/terminate_exception.h
  src/wase/ecs/entity.cpp
Labels: enhancement

#71 Linux support and continuous integration
  .github/workflows/cmake.yml
Labels: enhancement

#75 Added testing
  .github/workflows/cmake.yml
  CMakeLists.txt
  test/component_test.cpp
  test/entity_test.cpp
  test/main_test.cpp
Labels: enhancement

#76 Updated readme.md
  readme.md
Labels: documentation

#77 Updated readme.md
  readme.md
Labels: documentation

#80 Updated the readme.md and CONTRIBUTING.md and got rid of a warning
  CONTRIBUTING.md
  readme.md
  src/wase/core/renderer.cpp
Labels: documentation

#81 Updated the readme.md and CONTRIBUTING.md and got rid of a warning
  CONTRIBUTING.md
  readme.md
  src/wase/core/renderer.cpp
Labels: documentation

#82 Updated readme.md
  readme.md
Labels: documentation

#83 Updated readme.md
  readme.md
Labels: documentation
